### PR TITLE
Add board lettering (SAN)

### PR DESCRIPTION
**Pull request by l0c0f1x**
Hi,
I really like Dreamchess so far, but I always thought it's missing board lettering.

This PR adds an option "Board Lettering", that defaults to "Inactive" to be non intrusive and the code to load lettering textures. I also created suitable textures for each board style, see attached screenshots.
I'm sure it could be better looking, but I'm neither a game dev nor a designer, I just GIMPed around a little ;)
For the .xcf I've created a companion PR [dreamchess-tools#4](https://github.com/dreamchess/dreamchess-tools/pull/4) in [dreamchess-tools](https://github.com/dreamchess/dreamchess-tools).

Let me know if anything is wrong and I'll be happy to fix it.
Cheers

san-lettering-classic
san-lettering-elements
san-lettering-sketch
2020-07-14-155017_1920x1080_scrot

### CODE REVIEW

**Comment by CavernDigger88** [comment]
I just wanted to leave a comment. 

I patched the lettering into version that comes with Ubuntu 20.04 locally. It works great.
Any progress on getting "Figurine" to work?

**Comment by l0c0f1x** [comment]
> I just wanted to leave a comment.
> 
> I patched the lettering into version that comes with Ubuntu 20.04 locally. It works great.
> Any progress on getting "Figurine" to work?

Sorry for the late reply. Nice to know, it get's used somewhere :)

It has been a while since I took a look at the "Figurine" lettering: The problem is that this board style somehow gets dynamically generated from the files in the [figurine](https://github.com/dreamchess/dreamchess/tree/master/dreamchess/data/pieces/figurine) folder while all other styles have a static board texture in a subfolder of [styles](https://github.com/dreamchess/dreamchess/tree/master/dreamchess/data/styles). I could not figure out how this generation is done and just guessed that the [flat.dcm](https://github.com/dreamchess/dreamchess/blob/master/dreamchess/data/pieces/figurine/flat.dcm) has to be central to that process as this seems to be the model on which the textures get mapped.
So for all other styles I just created a (transparent) static texture matching the dimensions of the board texture and used that as an overlay. Now, if I use a static "figurine" lettering texture and render that as an overlay it gets mispositioned.
To answer your question: Unfortunately there has been no progress in getting this to work but I will try to find the time to take another shot at it.

**Comment by waltervn** [comment]
I don't know exactly why it doesn't work, but some background info:

There's two elements to rendering the board:
1) The middle part containing the squares: the code for this is inside the engine and uses the middle part of the board texture
2) The edge of the board. This is the .dcm model file. It uses the edges of that same board texture

What's different about figurine is that it has no board edge and if you open the flat.dcm file (it's just a text file), you'll see it's essentially empty. I don't know exactly how this affects your lettering patch, but it's probably somehow related to this.

**Comment by waltervn** [comment]
I looked into it a bit further, since the lettering patch uses the dcm as well, and flat.dcm is empty, it makes sense that the lettering doesn't show up. So I guess one way to fix this would be to add a transparent board edge to the figurine theme. You could perhaps try to just copy sketch.dcm to flat.dcm, since that uses a similar flat board IIRC.

**Comment by l0c0f1x** [comment]
Yeah that makes sense. Because the lettering has to be rendered on the board edge the lettering textures for the other styles are created in exactly that way. If you overlay them manually with the board textures, they fit. So if one tries to render the lettering on figurine using the dcm, the origin of rendering coordinates is already the upper left corner of the middle part and does not include the "padding" (in lack of a better term) of the board edge.
Ok, I will try your suggestion and see how it goes. How are the dcm files generated, by the way? Thanks in advance.

**Comment by waltervn** [comment]
The .dcm format was created mainly because we needed triangle strips on Dreamcast, for performance reasons. It should be replaced with something standard, but until we address that we are stuck with it. They're exported from blender models with dcm_export.py. Then passed through a tool called dcmstrip (which uses a library called libtristripper). All the models/scripts/tools can be found in the dreamchess/dreamchess-tools repository. I have no idea how usable any of this is today though...

**Comment by l0c0f1x** [comment]
Yes! The dcm from "Sketch" and transparent edge on "Figurine" did the trick, thanks. I updated the PR by amending and rebasing the old commit. I also updated the companion PR [dreamchess-tools#4](https://github.com/dreamchess/dreamchess-tools/pull/4) by amending the old commit over there. And thanks for the info on the .dcm format.

**Comment by waltervn** [comment]
Indeed, I should have said flat/board.dcm (flat.dcm is not empty).

Regarding the patch, the only thing I'd probably like to see changed is to make it use On/Off like the full_screen option instead of Active/Inactive, and also query it the same way using the selected index (remove the malloc). Your implementation allows for the order of the options to be swapped without changing the code, which is a plus, but I still think I'd prefer to keep things simple (albeit perhaps slightly more hackish) and have it work like the full_screen option.

If you don't feel like making these changes that's OK, I'll look at it once we get the unicode stuff done.

Either way, we're planning to include this in the next version, thanks a lot!

**Comment by l0c0f1x** [comment]
Sure, no worries - a consistent UI and implementation make sense. I just won't get to it in the next couple of days, but I will implement the changes.
>Either way, we're planning to include this in the next version, thanks a lot!

Cool! You're welcome :)

**Comment by l0c0f1x** [comment]
OK, the changes are implemented now, On/Off are used for labeling and the option gets queried by index. To avoid duplicating the query code I left the `get_is_lettering` and `set_is_lettering` methods.
I also updated the localization files properly.

**Comment by waltervn** [comment]
This has been rebased and merged in. I decided to rename "lettering" to "coordinates", to bring it more in line with other programs like xboard. 

Thanks!

**Pull request closed without merging**
